# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
#
#/tracking/verbose 1
/control/verbose 2
/run/verbose 2

#
# gamma 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
/gun/particle gamma
/gun/energy 10 MeV
#
/run/printProgress 1000
/run/beamOn 1000000

#/gun/particle mu+
#/gun/energy 10 MeV
#/run/printProgress 1000
#/run/beamOn 1000


